version: '2.2'

services:

# cron services
  gosh-cron-rem-rotate-small: &service
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: gosh-cron-rem-rotate-small
    init: true
    restart: "on-failure"
    environment: ["GM_MODE=cron-rem-rotate-small"]
    volumes:
      - "../config:/home/node/app/config:ro"
      - "./errors:/home/node/app/errors"
      - "gm-cron-rem-rotate-small-data:/home/node/app/data"
    networks:
      monitor-net: { }

  gosh-cron-rem-rotate-large:
    <<: *service
    container_name: gosh-cron-rem-rotate-large
    environment: ["GM_MODE=cron-rem-rotate-large"]
    volumes:
      - "../config:/home/node/app/config:ro"
      - "./errors:/home/node/app/errors"
      - "gm-cron-rem-rotate-large-data:/home/node/app/data"


networks:
  monitor-net:
    external:
      name: dockprom_monitor-net

volumes:
  gm-cron-rem-rotate-small-data:
  gm-cron-rem-rotate-large-data:
