global:
  seed:          ###SECRET###
  organization:  monitoring
  repository:    monitoring
  branch:        INVALID
  filename:      last
  handler:       INVALID
  large:         false
  prefix:        gosh_mon_
  timeout:       20000
  root:          0:ac3c0b77666343d8a3497469a9a26a8c8eed4d8fba8dfa3c64e0503f81d74ab0
  interval:      45
  subinterval:   0
  origin:        INVALID
  cron:          false
  appurl:        https://app.gosh.sh/
  pupextraflags: []
# pupextraflags: ['--unsafely-treat-insecure-origin-as-secure=http://gosh.matusevich.pro']
# gosh_repo_url: https://github.com/tonlabs/gosh.git
# gosh_branch:   main
# gosh_bin_path: git-remote-gosh/git-remote-gosh.js
  gosh_repo_url: https://github.com/gosh-sh/gosh.git
  gosh_branch:   "release:latest"
  gosh_bin_path: last-git-remote-gosh
  release_asset: git-remote-gosh-amd64


includes:

  next: &next
    # for app.gosh.sh
    appurl: https://goshnext.services.tonlabs.io/
    # for remote
    # gosh_repo_url: https://github.com/gosh-sh/gosh.git
    # gosh_branch:   "release:latest"
    # gosh_bin_path: git-remote-gosh/bin/git-remote-gosh

#  cron-rotate: &cron-rotate
#    origin: ticker-root
#    handler: app-rotate
#    cron: true


modes:

# app.gosh.sh
  app-small-read: &app-small-read
    branch:  ticker-app-small
    handler: app-read
    large:   false

  app-small-write: &app-small-write
    branch:  ticker-app-small
    handler: app-write
    large:   false
    interval: 200

  app-large-read: &app-large-read
    branch:  ticker-app-large
    handler: app-read
    large:   true
    timeout: 15000

  app-large-write: &app-large-write
    branch:  ticker-app-large
    handler: app-write
    large:   true
    timeout: 15000
    interval: 450

  app-small-read-next:
    <<: *app-small-read
    <<: *next

  app-small-write-next:
    <<: *app-small-write
    <<: *next

  app-large-read-next:
    <<: *app-large-read
    <<: *next

  app-large-write-next:
    <<: *app-large-write
    <<: *next

  # extension-ui.gosh.sh
  ext-small-read:
    branch:  ticker-app-small
    handler: extui-read
    large:   false

  ext-large-read:
    branch:  ticker-app-large
    handler: extui-read
    large:   true
    timeout: 15000

# git-remote-gosh
  rem-small-read: &rem-small-read
    branch:  ticker-remote-small
    handler: remote-read
    large:   false
    timeout: 50

  rem-small-write: &rem-small-write
    branch:  ticker-remote-small
    handler: remote-write
    large:   false
    interval: 150
    timeout: 270

  rem-large-read: &rem-large-read
    branch:  ticker-remote-large
    handler: remote-read
    large:   true
    timeout: 50

  rem-large-write: &rem-large-write
    branch:  ticker-remote-large
    handler: remote-write
    large:   true
    interval: 450
    timeout: 270

#  rem-small-read-next:
#    <<: *rem-small-read
#    <<: *next
#
#  rem-small-write-next:
#    <<: *rem-small-write
#    <<: *next
#
#  rem-large-read-next:
#    <<: *rem-large-read
#    <<: *next
#
#  rem-large-write-next:
#    <<: *rem-large-write
#    <<: *next
#
# rotation cron
#  cron-rem-rotate-test:
#    <<: *cron-rotate
#    branch:  test-branch
#
#  cron-rem-rotate-small:
#    <<: *cron-rotate
#    branch:  ticker-remote-small
#
#  cron-rem-rotate-large:
#    <<: *cron-rotate
#    branch:  ticker-remote-large
#    large:   true
