name: GitHub Actions Demo
on: [push]

jobs:


  build-and-release:
    name: Build and Release
    needs: create_release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-2019
            bin: sad
          - os: ubuntu-20.04
            bin: asd
          - os: macos-12
            bin: sad
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.66.0
          override: true
      - name: run if Ubuntu only
        if: startsWith(matrix.os,'ubuntu')
        run: |
          sudo apt install -y protobuf-compiler
      - name: run if MacOS only
        if: startsWith(matrix.os,'macos')
        run: |
          brew install protobuf
      - name: run if Windows only
        if: startsWith(matrix.os,'windows')
        run: |
          choco install protoc
      - name: Prepare ABIs
        working-directory: git-remote-gosh
        run: |
          mkdir -p ./resources
          cp ../contracts/gosh/*.abi.json ./resources/
      - name: Build project
        working-directory: git-remote-gosh
        run: |
          cargo build --release
          ls -la bin
          cat bin/run.sh
          ls -la target
          ls -la target/release
          ls -la target/release/git-remote-gosh
