name: GitHub Actions Demo
on: [push]

jobs:
  release:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
          - os: macos-12
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        working-directory: git-remote-gosh
        run: cargo build --release