name: build and release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

permissions:
  contents: write

jobs:
  build:
    name: ${{ matrix.platform.os_name }} with rust ${{ matrix.toolchain }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - release_name: git-remote-gosh-linux-arm64
            os: ubuntu-20.04
            target: aarch64-unknown-linux-musl
            bin: git-remote-gosh_v6_1_0
          - release_name: git-remote-gosh-linux-amd64
            os: ubuntu-20.04
            target: x86_64-unknown-linux-musl
            bin: git-remote-gosh_v6_1_0
          - release_name: git-remote-gosh-windows-amd64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: git-remote-gosh_v6_1_0.exe
          - release_name: git-remote-gosh-darwin-arm64
            os: macos-latest
            target: aarch64-apple-darwin
            bin: git-remote-gosh_v6_1_0
          - release_name: git-remote-gosh-darwin-amd64
            os: macos-latest
            target: x86_64-apple-darwin
            bin: git-remote-gosh_v6_1_0
        toolchain:
          - stable
    steps:
      # - uses: actions/checkout@v4

      # - name: Copy ABI
      #   working-directory: v6_x/v6.1.0/git-remote-gosh
      #   run: |
      #     make copy_abi

      # - name: Build binary
      #   uses: houseabsolute/actions-rust-cross@v0
      #   with:
      #     command: build
      #     working-directory: v6_x/v6.1.0/git-remote-gosh
      #     target: ${{ matrix.platform.target }}
      #     toolchain: ${{ matrix.toolchain }}
      #     args: --release
      #     strip: true

      - name: Fake build
        if: startsWith(matrix.platform.os, 'windows') != true
        run: |
          mkdir -p v6_x/v6.1.0/git-remote-gosh/target/${{ matrix.platform.target }}/release
          touch v6_x/v6.1.0/git-remote-gosh/target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}
          ls -lA v6_x/v6.1.0/git-remote-gosh/target/${{ matrix.platform.target }}/release

      - name: Prepare release (not windows)
        if: startsWith(matrix.platform.os, 'windows') != true
        run: |
          mkdir -p ${{ matrix.platform.target }}
          mv v6_x/v6.1.0/git-remote-gosh/target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }} ${{ matrix.platform.release_name }}
          tar -czvf ${{ matrix.platform.release_name }}.tar.gz ${{ matrix.platform.release_name }}

      - name: Release binary
        uses: softprops/action-gh-release@v1
        if: startsWith(matrix.platform.os, 'windows') != true
        with:
          files: |
            ${{ matrix.platform.release_name }}.tar.gz
          prerelease: true
          tag_name: rc-${{ github.ref_name }}-${{ github.run_number }}
