name: Dispatcher

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on:
      - ubuntu-latest
      - macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cd gosh-dispatcher && cargo build --verbose --release
